# Load-tests the alert-dispatch pipeline: FastAPI-> Redis(Celery broker)-> Celery worker(gevent pool)-> SMTP. 
# Fires N concurrent POST /alerts/dispatch requests, then polls every resulting task_id until
# it reaches a terminal Celery state (SUCCESS/FAILURE) or times out, and
# reports latency percentiles + throughput for both phases.
# REQUIRES ENTIRE STACK RUNNING FIRST: 
#   1. docker run ... (Redis)
#   2. celery -A app.core.celery_app.celery_app worker --pool=gevent --concurrency=100
#   3. uvicorn app.main:app
# Usage:
#   python loader.py                    # 150 concurrent requests, defaults
#   python loader.py --n 300 --timeout 45
#   python loader.py --api-base http://127.0.0.1:8000

from __future__ import annotations
import argparse
import asyncio
import statistics
import time
from dataclasses import dataclass
import httpx

@dataclass
class SubmitResult:
    index: int
    task_id: str | None
    submit_latency: float
    error: str | None = None

@dataclass
class CompletionResult:
    index: int
    task_id: str
    status: str
    completion_latency: float  # measured from batch start, not this request's own submit time
    timed_out: bool = False

async def submit_one(client: httpx.AsyncClient, index: int, api_base: str) -> SubmitResult:
    payload = {
        "subject": f"[Load Test] alert #{index}",
        "body": f"Synthetic load-test alert #{index} generated by loader.py",
        "to": None,
    }
    start = time.monotonic()
    try:
        resp = await client.post(f"{api_base}/alerts/dispatch", json=payload)
        resp.raise_for_status()
        task_id = resp.json()["task_id"]
        return SubmitResult(index=index, task_id=task_id, submit_latency=time.monotonic() - start)
    except Exception as exc:
        return SubmitResult(index=index, task_id=None, submit_latency=time.monotonic() - start, error=str(exc))

async def poll_one(
    client: httpx.AsyncClient,
    index: int,
    task_id: str,
    api_base: str,
    poll_interval: float,
    timeout: float,
    batch_start: float,
) -> CompletionResult:
    deadline = batch_start + timeout
    while True:
        resp = await client.get(f"{api_base}/alerts/dispatch/{task_id}")
        resp.raise_for_status()
        data = resp.json()
        if data["status"] in ("SUCCESS", "FAILURE"):
            return CompletionResult(
                index=index,
                task_id=task_id,
                status=data["status"],
                completion_latency=time.monotonic() - batch_start,
            )
        if time.monotonic() >= deadline:
            return CompletionResult(
                index=index,
                task_id=task_id,
                status=data["status"],
                completion_latency=time.monotonic() - batch_start,
                timed_out=True,
            )
        await asyncio.sleep(poll_interval)

def summarize(label: str, values: list[float]) -> str:
    if not values:
        return f"{label}: no data"
    values_sorted = sorted(values)

    def pct(p: float) -> float:
        idx = min(int(len(values_sorted) * p), len(values_sorted) - 1)
        return values_sorted[idx]

    return (
        f"{label}: min={min(values):.3f}s  p50={pct(0.50):.3f}s  "
        f"p95={pct(0.95):.3f}s  p99={pct(0.99):.3f}s  max={max(values):.3f}s  "
        f"mean={statistics.mean(values):.3f}s"
    )

async def run_loader(n: int, api_base: str, poll_interval: float, timeout: float, max_connections: int) -> None:
    limits = httpx.Limits(max_connections=max_connections, max_keepalive_connections=max_connections)
    async with httpx.AsyncClient(limits=limits, timeout=timeout) as client:
        print(f"Submitting {n} concurrent alert-dispatch requests to {api_base} ...")
        batch_start = time.monotonic()

        submit_results = await asyncio.gather(*[submit_one(client, i, api_base) for i in range(n)])
        submit_wall_time = time.monotonic() - batch_start

        ok_submits = [r for r in submit_results if r.task_id is not None]
        failed_submits = [r for r in submit_results if r.task_id is None]

        print(
            f"Submitted {len(ok_submits)}/{n} successfully in {submit_wall_time:.3f}s "
            f"({len(ok_submits) / submit_wall_time:.1f} req/s)"
        )
        if failed_submits:
            print(f"{len(failed_submits)} submit(s) failed outright, e.g.: {failed_submits[0].error}")

        if not ok_submits:
            print("Nothing to poll — all submits failed. Check that FastAPI/Redis/Celery are all running.")
            return

        print(f"Polling {len(ok_submits)} task(s) for completion (timeout={timeout}s each) ...")
        completion_results = await asyncio.gather(
            *[
                poll_one(client, r.index, r.task_id, api_base, poll_interval, timeout, batch_start)
                for r in ok_submits
            ]
        )

        succeeded = [r for r in completion_results if r.status == "SUCCESS" and not r.timed_out]
        task_failed = [r for r in completion_results if r.status == "FAILURE" and not r.timed_out]
        timed_out = [r for r in completion_results if r.timed_out]
        total_wall_time = time.monotonic() - batch_start

        print()
        print("=" * 60)
        print("LOAD TEST RESULTS")
        print("=" * 60)
        print(f"Requested:        {n}")
        print(f"Submitted OK:     {len(ok_submits)}")
        print(f"Completed OK:     {len(succeeded)}")
        print(f"Task FAILURE:     {len(task_failed)}")
        print(f"Timed out:        {len(timed_out)}")
        print()
        print(summarize("Submit latency  ", [r.submit_latency for r in ok_submits]))
        print(summarize("End-to-end time ", [r.completion_latency for r in completion_results]))
        print()
        print(f"Total wall time:            {total_wall_time:.3f}s")
        print(f"Effective throughput:       {len(succeeded) / total_wall_time:.2f} completed alerts/s")


def main() -> None:
    parser = argparse.ArgumentParser(description="Load test the alert-dispatch pipeline.")
    parser.add_argument("--n", type=int, default=150, help="Number of concurrent dispatch requests (default 150)")
    parser.add_argument("--api-base", type=str, default="http://127.0.0.1:8000", help="FastAPI base URL")
    parser.add_argument("--poll-interval", type=float, default=0.25, help="Seconds between status polls")
    parser.add_argument("--timeout", type=float, default=30.0, help="Per-task timeout in seconds")
    parser.add_argument("--max-connections", type=int, default=200, help="Max concurrent HTTP connections")
    args = parser.parse_args()

    asyncio.run(
        run_loader(
            n=args.n,
            api_base=args.api_base,
            poll_interval=args.poll_interval,
            timeout=args.timeout,
            max_connections=args.max_connections,
        )
    )

if __name__ == "__main__":
    main()