"""
Load test for the Team Task Management API.
Run with the stack up (docker compose -f docker/docker.compose.yml up -d):
    locust -f locustfile.py --host http://localhost:8000
Then open http://localhost:8089 to set concurrent users / spawn rate.
"""
import time
import uuid
from locust import HttpUser, task, between, events

class ApiUser(HttpUser):
    wait_time = between(0.5, 2)

    def on_start(self):
        """Runs once per simulated user: register, log in, create a project
        to work against for the rest of this user's session."""
        unique = uuid.uuid4().hex[:10]
        self.email = f"loadtest-{unique}@test.com"
        self.password = "LoadTest!23"
        # POST /auth/register — JSON body (UserCreate schema)
        self.client.post(
            "/auth/register",
            json={"name": f"Load Test {unique}", "email": self.email, "password": self.password},
            name="/auth/register",
        )
        # POST /auth/login — form-encoded (OAuth2PasswordRequestForm), NOT json
        resp = self.client.post(
            "/auth/login",
            data={"username": self.email, "password": self.password},
            name="/auth/login",
        )
        token = resp.json().get("access_token")
        self.headers = {"Authorization": f"Bearer {token}"}
        # Give this user a project to act on for the rest of its tasks
        resp = self.client.post(
            "/projects/",
            json={"name": f"Load Test Project {unique}"},
            headers=self.headers,
            name="/projects/ [create]",
        )
        self.project_id = resp.json().get("id")

    @task(5)
    def list_projects(self):
        self.client.get("/projects/", headers=self.headers, name="/projects/ [list]")

    @task(3)
    def get_project_stats(self):
        if self.project_id:
            self.client.get(
                f"/projects/{self.project_id}/stats",
                headers=self.headers,
                name="/projects/{id}/stats",
            )

    @task(3)
    def create_task(self):
        if self.project_id:
            self.client.post(
                "/tasks/",
                json={"title": "Load test task", "project_id": self.project_id},
                headers=self.headers,
                name="/tasks/ [create]",
            )

    @task(4)
    def list_project_tasks(self):
        if self.project_id:
            self.client.get(
                f"/tasks/project/{self.project_id}",
                headers=self.headers,
                name="/tasks/project/{id}",
            )

    @task(2)
    def get_my_tasks(self):
        self.client.get("/tasks/assigned/me", headers=self.headers, name="/tasks/assigned/me")

    @task(1)
    def get_me(self):
        self.client.get("/users/me", headers=self.headers, name="/users/me")


class AlertDispatchUser(HttpUser):
    """Reproduces loader.py's submit-then-poll pattern as a Locust task, so
    the async alert pipeline (FastAPI -> Redis -> Celery -> SMTP) gets
    stressed in the same run as ApiUser's ordinary CRUD traffic.
    Set this class's weight relative to ApiUser via --class-picker or by
    tuning `weight` below, e.g. weight = 1 while ApiUser implicitly has
    weight = 1 too means roughly a 50/50 split of simulated users between
    plain CRUD traffic and alert-dispatch traffic.
    """
    weight = 1
    wait_time = between(1, 3)
    POLL_INTERVAL = 0.25
    POLL_TIMEOUT = 30.0

    @task
    def dispatch_and_await_alert(self):
        payload = {
            "subject": f"[Load Test] alert #{uuid.uuid4().hex[:8]}",
            "body": "Synthetic load-test alert generated by locustfile.py",
            "to": None,
        }
        # Manual timing block so the poll-to-completion latency (not just
        # the initial 202) shows up as its own row in Locust's stats table.
        start = time.monotonic()
        with self.client.post(
            "/alerts/dispatch", json=payload, name="/alerts/dispatch [submit]",
            catch_response=True,
        ) as resp:
            if resp.status_code != 202:
                resp.failure(f"unexpected status {resp.status_code}")
                return
            task_id = resp.json()["task_id"]
        deadline = start + self.POLL_TIMEOUT
        with self.client.get(
            f"/alerts/dispatch/{task_id}", name="/alerts/dispatch/{id} [poll-to-completion]",
            catch_response=True,
        ) as resp:
            status = resp.json().get("status")
            while status not in ("SUCCESS", "FAILURE"):
                if time.monotonic() >= deadline:
                    resp.failure(f"timed out after {self.POLL_TIMEOUT}s, last status={status}")
                    return
                time.sleep(self.POLL_INTERVAL)
                poll = self.client.get(f"/alerts/dispatch/{task_id}", name="/alerts/dispatch/{id} [poll-to-completion]")
                status = poll.json().get("status")
            if status == "FAILURE":
                resp.failure("alert task ended in FAILURE")
            # SUCCESS falls through as a pass; Locust records the full
            # elapsed time of this `with` block as the request's response time.