"""add uniqueness constraints

Revision ID: 4e6a826265f7
Revises: 3450982e0e2d
Create Date: 2026-08-24 15:59:02.497973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6a826265f7'
down_revision: Union[str, Sequence[str], None] = '3450982e0e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['name'])
    op.create_unique_constraint('uq_task_project_title', 'tasks', ['project_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_project_title', 'tasks', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
