"""enforce single global admin

Revision ID: 860854fa6007
Revises: 4e6a826265f7
Create Date: 2026-08-25 15:22:45.908843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860854fa6007'
down_revision: Union[str, Sequence[str], None] = '4e6a826265f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_single_global_admin', 'users', ['global_role'], unique=True, postgresql_where=sa.text("global_role = 'admin'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_single_global_admin', table_name='users', postgresql_where=sa.text("global_role = 'admin'"))
    # ### end Alembic commands ###
