"""constraints added

Revision ID: cc87caec65c7
Revises: 860854fa6007
Create Date: 2026-08-26 16:11:17.254245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc87caec65c7'
down_revision: Union[str, Sequence[str], None] = '860854fa6007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_alerts', sa.Column('target_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_alerts', 'target_id')
    # ### end Alembic commands ###
